### ISSUE TITLE
Fusio Sample Adapter HTTP 

### ISSUE THREAD

**Issue by LeongTitanFour** [apioo/fusio-adapter-http#2]
Hi, sorry I disturb you but I need something to ask you.
Sometime I hard to understand on how to create the file for connecting to JDE with cronjob. 
Can you create the file for example Fusio Sample Adapter HTTP?

**Comment by chriskapp** [comment]
Hi, so Iam not really sure what you mean with JDE with cronjob but you could checkout our new docs page s.
https://docs.fusio-project.org/
Since the issue is really old I will close it for now.
